version: 2.1

orbs:
  node: circleci/node@7.0.0

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      # caching node_modules to avoid re-installing dependencies on every build
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
            - node-modules-
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Eslint
          command: npm run lint
      - run:
          name: Run Prettier
          command: npm run prettier
      - save_cache:
          paths:
            - ~/.npm
          key: node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Backend build
          command: npm run build

workflows:
  build-and-test:
    jobs:
      - build
