version: 2.1

orbs:
  node: circleci/node@7.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      # caching node_modules to avoid re-installing dependencies on every build
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
            - node-modules-
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run Eslint
          command: npm run lint
      - run:
          name: Run Prettier
          command: npm run prettier
      - save_cache:
          paths:
            - ~/.npm
          key: node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Backend build
          command: npm run build
  deploy:
    executor:
      name: node/default
    steps:
      - run:
          name: Execute custom deployment script
          command: npm run deploy
      - aws-elastic-beanstalk/deploy:
          name: Deploy to Elastic Beanstalk
          application-name: OnlineShopping
          environment-name: OnlineShopping-dev
          region: ca-central-1
          version-label: "build-${CIRCLE_BUILD_NUM}"

workflows:
  build-and-test:
    jobs:
      - build
      - deploy:
          requires:
            - build
