version: 2.1

orbs:
  node: circleci/node@7.0.0

jobs:
  build:
    executor:
      name: node/default
    # instead of hardcoding the node.js version in multiple places, use a variable
    parameters:
      node-version:
        type: string
        default: '18.16.1'
    steps:
      - checkout
      # caching node_modules to avoid re-installing dependencies on every build
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
            - node-modules-
      - node/install:
          # node-version variable here for consistency
          node-version: << parameters.node-version >>
      - save_cache:
          paths:
            - ~/.npm
          key: node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Backend build
          command: npm run build

workflows:
  build-and-test:
    jobs:
      - build
