version: 2.1

orbs:
  node: circleci/node@7.0.0
  aws-elastic-beanstalk: circleci/aws-elastic-beanstalk@2.0.1

executors:
  python-executor:
    docker:
      - image: cimg/python:3.8

jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - restore_cache:
          keys:
            - node-modules-{{ checksum "package-lock.json" }}
            - node-modules-
      - node/install-packages:
          pkg-manager: npm
      - run:
          name: Run ESLint
          command: npm run lint
      - run:
          name: Run Prettier
          command: npm run prettier
      - save_cache:
          paths:
            - ~/.npm
          key: node-modules-{{ checksum "package-lock.json" }}
      - run:
          name: Backend Build
          command: npm run build

  deploy:
    executor: python-executor
    steps:
      - checkout
      - run:
          name: Install EB CLI
          command: |
            pip install awsebcli --upgrade
            eb --version
      - run:
          name: Execute custom deployment script
          command: eb deploy --staged


workflows:
  build-and-test:
    jobs:
      - build
      - deploy:
          requires:
            - build
      - aws-elastic-beanstalk/deploy:
          name: Deploy to Elastic Beanstalk
          application-name: OnlineShopping
          environment-name: OnlineShopping-dev
          requires:
            - deploy
